[alias]
summary = "run -p c_assess_inf --bin summarise_scores"
gen_phrx_skipfail = "run --manifest-path a_data/preproc/rephras/Cargo.toml --bin generate_paraphrases_skipfail --release --"
results_assess = "run --manifest-path c_assess_inf/Cargo.toml --bin results_assess --release --"
jsmerge = "run --manifest-path c_assess_inf/Cargo.toml --bin merge_jsons --release --"
jssplit = "run --manifest-path c_assess_inf/Cargo.toml --bin split_jsons --release --"
instructmerge = "run --manifest-path c_assess_inf/Cargo.toml --bin merge_instructs --release --"
results_assess  = "run -p c_assess_inf --bin results_assess"
add_scenarios = "run --manifest-path a_data/preproc/rephras/Cargo.toml --bin add_scenarios --release --"
