#!/bin/bash
#PBS -N sy-la-co_1-2_prx_alpaca_gen_phrx
#PBS -l select=1:ncpus=8:mem=64gb
#PBS -l walltime=65:00:00
#PBS -o logs/sy-la-co_1-2_prx_alpaca_gen_phrx.out
#PBS -e logs/sy-la-co_1-2_prx_alpaca_gen_phrx.err

# Move to the directory from which the job was submitted
cd "$PBS_O_WORKDIR"
. "$HOME/.cargo/env"

echo "$(date "+%Y-%m-%d %H:%M:%S") - sy-la-co_1-2_prx_alpaca_gen_phrx started" >> "$HOME/times.log"

export GOOGLE_API_KEY=""

# Path to the Rust workspace
MANIFEST_PATH="$PBS_O_WORKDIR/a_data/preproc/rephras/Cargo.toml"

# choice:
#const MODEL: &str = "gemini-2.5-pro-preview-05-20";
#const MODEL: &str = "gemini-2.5-flash-preview-05-20";
#const MODEL: &str = "gemini-2.5-pro-preview-05-06";
#const MODEL: &str = "gemini-2.5-flash-preview-04-17";

for SLICE in 1 2
    do
    IN_JSON="a_data/alpaca/slice_100/alpaca_slice"$SLICE".json"

    for TYPE in syntax language context
        do
        OUT_JSON="a_data/alpaca/slice_100/prxed_"$TYPE"_slice"$SLICE".json"
        # Run the Rust program
        cargo run \
            --manifest-path "$MANIFEST_PATH" \
            --release -- \
            --version-set "$TYPE" \
            --model "gemini-2.5-pro-preview-05-20" \
            "$IN_JSON" \
            "$OUT_JSON"
    done
done

echo "$(date "+%Y-%m-%d %H:%M:%S") - sy-la-co_1-2_prx_alpaca_gen_phrx finished" >> "$HOME/times.log"
