#!/bin/bash
#PBS -N gs_g2_language_run_inf
#PBS -l select=1:ncpus=8:ngpus=1:mem=79gb
#PBS -l walltime=10:00:00
#PBS -o logs/gs_g2_language_run_inf.out
#PBS -e logs/gs_g2_language_run_inf.err

# Move to the directory from which job submitted
cd $PBS_O_WORKDIR

echo "$(date "+%Y-%m-%d %H:%M:%S") - gs_g2_language_run_inf started" >> $HOME/times.log
nvidia-smi --query-gpu=name --format=csv,noheader

#export MODEL_NAME="google/gemma-2-2b-it"
#export MODEL_NAME="google/gemma-2-9b-it"
#export MODEL_NAME="Qwen/Qwen1.5-1.8B"

# language

# Paths
CONTAINER_PATH="$PBS_O_WORKDIR/containers/hf_cont.sif"
SCRIPT_PATH="$PBS_O_WORKDIR/c_assess_inf/src/inference_run_betterbatch.py"

# Run the script inside the container
singularity exec --nv \
    "$CONTAINER_PATH" \
    python "$SCRIPT_PATH" \
        a_data/gsm8k/prxed_main_500/language.json \
        c_assess_inf/output/gsm8k/gemma-2-2b-it/language.json \
        --model google/gemma-2-2b-it \
        --batch 16 \
        --log_every 90 \
        --type language \
        --temperature 0 \
        --max_tokens 256 \
        --device cuda:0

echo "$(date "+%Y-%m-%d %H:%M:%S") - gs_g2_language_run_inf finished" >> $HOME/times.log
