#!/bin/bash
#PBS -N a_q2_language_run_inf
#PBS -l select=1:ncpus=8:ngpus=1:mem=49gb
#PBS -l walltime=15:00:00
#PBS -o logs/a_q2_language_run_inf.out
#PBS -e logs/a_q2_language_run_inf.err

# Move to the directory from which job submitted
cd $PBS_O_WORKDIR

echo "$(date "+%Y-%m-%d %H:%M:%S") - a_q2_language_run_inf started" >> $HOME/times.log
nvidia-smi --query-gpu=name --format=csv,noheader

#export MODEL_NAME="google/gemma-2-2b-it"
#export MODEL_NAME="google/gemma-2-9b-it"
#export MODEL_NAME="Qwen/Qwen2.5-3B-Instruct"
#export MODEL_NAME="Qwen/Qwen1.5-1.8B"
# language

# Paths
CONTAINER_PATH="$PBS_O_WORKDIR/containers/hf_cont.sif"
SCRIPT_PATH="$PBS_O_WORKDIR/c_assess_inf/src/inference_run_betterbatch.py"

# Run the script inside the container
singularity exec --nv \
    "$CONTAINER_PATH" \
    python "$SCRIPT_PATH" \
        a_data/alpaca/slice_500/language.json \
        c_assess_inf/output/alpaca_prxed/Qwen2.5-3B-Instruct/language.json \
        --model Qwen/Qwen2.5-3B-Instruct \
        --batch 16 \
        --log_every 120 \
        --type language \
        --temperature 0 \
        --max_tokens 256

echo "$(date "+%Y-%m-%d %H:%M:%S") - a_q2_language_run_inf finished" >> $HOME/times.log
