#!/bin/bash
#PBS -N mm_q_obstruction_run_inf
#PBS -l select=1:ncpus=8:ngpus=1:mem=39gb
#PBS -l walltime=05:00:00
#PBS -o logs/mm_q_obstruction_run_inf.out
#PBS -e logs/mm_q_obstruction_run_inf.err

# Move to the directory from which job submitted
cd $PBS_O_WORKDIR

echo "$(date "+%Y-%m-%d %H:%M:%S") - mm_q_obstruction_run_inf started" >> $HOME/times.log
nvidia-smi --query-gpu=name --format=csv,noheader

#export MODEL_NAME="google/gemma-2-2b-it"
#export MODEL_NAME="google/gemma-2-9b-it"
#export MODEL_NAME="Qwen/Qwen1.5-1.8B"

# obstruction

# Paths
CONTAINER_PATH="$PBS_O_WORKDIR/containers/hf_cont.sif"
SCRIPT_PATH="$PBS_O_WORKDIR/c_assess_inf/src/inference_run_mmlu.py"

# Run the script inside the container
singularity exec --nv \
    "$CONTAINER_PATH" \
    python "$SCRIPT_PATH" \
        a_data/mmlu/prxed_moral_500_scenarios/obstruction.json \
        c_assess_inf/output/mmlu/Qwen1.5-1.8B/obstruction.json \
        --model Qwen/Qwen1.5-1.8B \
        --batch 32 \
        --log_every 90 \
        --type obstruction \
        --temperature 0 \
        --max_tokens 256 \
        --device cuda:0

echo "$(date "+%Y-%m-%d %H:%M:%S") - mm_q_obstruction_run_inf finished" >> $HOME/times.log
