#!/bin/bash
#PBS -N g2_spec_char_gsm8k_run_inf
#PBS -l select=1:ncpus=8:ngpus=1:mem=49gb
#PBS -l walltime=07:00:00
#PBS -o logs/g2_spec_char_gsm8k_run_inf.out
#PBS -e logs/g2_spec_char_gsm8k_run_inf.err

# Move to the directory from which job submitted
cd $PBS_O_WORKDIR

echo "$(date "+%Y-%m-%d %H:%M:%S") - g2_spec_char_gsm8k_run_inf started" >> $HOME/times.log
nvidia-smi --query-gpu=name --format=csv,noheader

#export MODEL_NAME="google/gemma-2-2b-it"
#export MODEL_NAME="Qwen/Qwen1.5-1.8B"
# spec_char

# Paths
CONTAINER_PATH="$PBS_O_WORKDIR/containers/hf_cont.sif"
SCRIPT_PATH="$PBS_O_WORKDIR/c_assess_inf/src/inference_run.pyy"

# Run the script inside the container
singularity exec --nv \
    "$CONTAINER_PATH" \
    python "$SCRIPT_PATH" \
        a_data/gsm8k/prxed_main_500/spec_char.json \
        c_assess_inf/output/gsm8k/gemma-2-2b-it/spec_char.json \
        --model Qwen/Qwen1.5-1.8B"\
        --batch 64 \
        --log_every 90 \
        --type gsm8k \
        --temperature 0 \
        --max_tokens 256 \
        --device cuda:0

echo "$(date "+%Y-%m-%d %H:%M:%S") - g2_spec_char_gsm8k_run_inf finished" >> $HOME/times.log
