#!/bin/bash
#PBS -N g9_voiceice1_run_inf
#PBS -l select=1:ncpus=8:ngpus=1:mem=39gb
#PBS -l walltime=05:00:00
#PBS -o logs/g9_voiceice1_run_inf.out
#PBS -e logs/g9_voiceice1_run_inf.err

# Move to the directory from which job submitted
cd $PBS_O_WORKDIR

echo "$(date "+%Y-%m-%d %H:%M:%S") - g9_voiceice1_run_inf started" >> $HOME/times.log
nvidia-smi --query-gpu=name --format=csv,noheader

#export MODEL_NAME="google/gemma-2-2b-it"
#export MODEL_NAME="google/gemma-2-9b-it"
#export MODEL_NAME="Qwen/Qwen1.5-1.8B"
# voice
# ice1

#done q: voice voice voice voice obxtruction,   queued spec, voice, voice

# Paths
CONTAINER_PATH="$PBS_O_WORKDIR/containers/hf_cont.sif"
SCRIPT_PATH="$PBS_O_WORKDIR/c_assess_inf/src/run_inference_batched_type.py"

# Run the script inside the container
singularity exec --nv \
    "$CONTAINER_PATH" \
    python "$SCRIPT_PATH" \
        a_data/alpaca/slice_100/voice_slice1.json \
        c_assess_inf/output/alpaca_newphras/gemma-2-9b-it/voiceice1_infresult.json \
        --model google/gemma-2-9b-it \
        --batch 32 \
        --log_every 90 \
        --type voice
        --temperature 0 \
        --max_tokens 256 \
        --device cuda:0

echo "$(date "+%Y-%m-%d %H:%M:%S") - g9_voiceice1_run_inf finished" >> $HOME/times.log
